create table if not exists WATERORDER(
ORDER_ID int primary key auto_increment,
FARM_ID NUMBER(5),
START_DATE_TIME TIMESTAMP,
ORDER_PLACE_TIME TIMESTAMP,
ORDER_CANCEL_TIME TIMESTAMP,
DURATION NUMBER(5),
STATUS VARCHAR(100));
